feat: item등록 기능 구현 및 테스트
ajou-capstone/campus-market-spring pull request #29
Opened 2024-11-01 12:46 UTC by sms3025

test: userRepository test 추가
campus 없는 유저 체크 테스트 추가 및 itemRepositoy 캠퍼스 관련
테스트 삭제
feat: item의 category 값들을 반환해주는 기능 추가 및 테스트

2024-11-01 17:43 UTC, zihang98 reviewed
ok

2024-11-02 03:30 UTC, kwon204 requested changes

2024-11-02 03:30 UTC, kwon204 commented on src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
> +    INVALID_ITEM_PHOTOS_SIZE(HttpStatus.BAD_REQUEST, 4020, "아이템 사진 개수가 5개를 초과했습니다."),
INVALID_ITEM_PHOTO_SIZE라는 의미가 사진 갯수라는 의미로 잘 안 받아들여지는 데 수정하면 안되나요
이미지 갯수가 아니라 이미지 크기랑 헷갈림

2024-11-02 03:30 UTC, kwon204 commented on src/main/java/LinkerBell/campus_market_spring/controller/ItemController.java
> +                throw new CustomException(ErrorCode.DUPLICATE_ITEM_PHOTOS);
중복 이미지라는게 url만으로 비교하는 걸 의도한건지 궁금함
참고로 s3에 이미지 저장할 때 동일한 이미지가 저장될 수 있음.

2024-11-02 03:30 UTC, kwon204 commented on src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
> +    INVALID_VERIFICATION_CODE(HttpStatus.UNAUTHORIZED, 4019, "인증 코드가 일치하지 않습니다."),
인증 코드 불일치 에러는 BAD_REQUEST가 맞음.
바꿔야함

2024-11-02 03:38 UTC, sms3025 commented on src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
> +    INVALID_ITEM_PHOTOS_SIZE(HttpStatus.BAD_REQUEST, 4020, "아이템 사진 개수가 5개를 초과했습니다."),
수정하겠음

2024-11-02 03:40 UTC, sms3025 commented on src/main/java/LinkerBell/campus_market_spring/controller/ItemController.java
> +                throw new CustomException(ErrorCode.DUPLICATE_ITEM_PHOTOS);
하나의 게시물에 같은 이미지 여러개 올리는걸 방지하는걸 의미함.  Url만으로 비교하는걸 의도한게 맞음.

2024-11-02 03:41 UTC, sms3025 commented on src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
> +    INVALID_VERIFICATION_CODE(HttpStatus.UNAUTHORIZED, 4019, "인증 코드가 일치하지 않습니다."),
수정하겠음

2024-11-02 03:45 UTC, kwon204 commented on src/main/java/LinkerBell/campus_market_spring/controller/ItemController.java
> +                throw new CustomException(ErrorCode.DUPLICATE_ITEM_PHOTOS);
일단 저렇게 하면 같은 이미지가 올라갈 수 있음(url은 다름)

2024-11-02 03:54 UTC, sms3025 commented on src/main/java/LinkerBell/campus_market_spring/controller/ItemController.java
> +                throw new CustomException(ErrorCode.DUPLICATE_ITEM_PHOTOS);
ㅇㅋ 근데 그거는 어떻게 하기가 어려워서 최소한의 중복검증만 하는거임

2024-11-02 05:11 UTC, closed without merging