feat: item 상세 정보 보기 기능 구현 및 테스트
ajou-capstone/campus-market-spring pull request #33
Opened 2024-11-04 11:20 UTC by sms3025

style: google java style 적용

2024-11-04 15:58 UTC, kwon204 requested changes

2024-11-04 15:58 UTC, kwon204 commented on src/main/java/LinkerBell/campus_market_spring/dto/ItemDetailsViewResponseDto.java
> +    private boolean isLiked;
"is" prefix 사용할 때 @JsonProperty(value = "isLiked")로 명시해야함

2024-11-04 15:58 UTC, kwon204 commented on src/test/java/LinkerBell/campus_market_spring/controller/ItemControllerTest.java
> +            .andExpect(jsonPath("$.code").value(4026));
ErrorCode.INVALID_ITEM_ID.getCode()로 바꿀 수 있음

2024-11-05 04:11 UTC, sms3025 commented on src/main/java/LinkerBell/campus_market_spring/dto/ItemDetailsViewResponseDto.java
> +    private boolean isLiked;
ok

2024-11-05 04:20 UTC, sms3025 commented on src/test/java/LinkerBell/campus_market_spring/controller/ItemControllerTest.java
> +            .andExpect(jsonPath("$.code").value(4026));
ok 수정했음

2024-11-05 04:23 UTC, closed without merging