feat : 채팅 관련 기능들 추가
ajou-capstone/campus-market-spring pull request #34
Opened 2024-11-04 11:37 UTC by zihang98

채팅 관련 기능들 추가

2024-11-04 16:19 UTC, kwon204 requested changes

2024-11-04 16:19 UTC, kwon204 commented on src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
> +        messagingTemplate.convertAndSend("/send/chat" + chatRoomId, chattingResponseDto);
/send/chat/{chatRoomId} <- 이렇게 돼야하는거 아닌가요?

2024-11-04 16:19 UTC, kwon204 commented on src/main/java/LinkerBell/campus_market_spring/dto/AuthUserDto.java
> +@Setter
이거 왜 추가된건가요?

2024-11-04 16:38 UTC, zihang98 commented on src/main/java/LinkerBell/campus_market_spring/dto/AuthUserDto.java
> +@Setter
chatRoomServiceTest에서 사용했음

2024-11-04 16:38 UTC, kwon204 commented on src/main/java/LinkerBell/campus_market_spring/dto/AuthUserDto.java
> +@Setter
지워주세요

2024-11-04 16:44 UTC, zihang98 commented on src/main/java/LinkerBell/campus_market_spring/dto/AuthUserDto.java
> +@Setter
dto에 setter 있으면 안좋은가?

2024-11-04 16:46 UTC, zihang98 commented on src/main/java/LinkerBell/campus_market_spring/controller/ChattingController.java
> +        messagingTemplate.convertAndSend("/send/chat" + chatRoomId, chattingResponseDto);
그러네요;;

2024-11-05 04:24 UTC, ajou4095 commented on src/main/generated/LinkerBell/campus_market_spring/dto/QItemSearchResponseDto.java
> +package LinkerBell.campus_market_spring.dto;
Generated 왜 코드에 포함되어있음?

2024-11-05 04:24 UTC, ajou4095 commented on src/main/java/LinkerBell/campus_market_spring/dto/RecentChatMessageResponseDto.java
> +    private Long chatRoomId;
이거 왜던짐?

2024-11-05 04:40 UTC, kwon204 commented on src/main/java/LinkerBell/campus_market_spring/dto/AuthUserDto.java
> +@Setter
필요없는데 있을 이유가 없어요

2024-11-05 05:09 UTC, sms3025 commented on src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
> +    MESSAGE_NOT_FOUND(HttpStatus.NOT_FOUND, 4027, "채팅 메시지가 존재하지 않습니다."),
에러 코드 겹치는데 혹시 수정해서 올려주실수 있는지?

2024-11-05 05:09 UTC, sms3025 commented on src/main/java/LinkerBell/campus_market_spring/repository/ChatMessageRepository.java
> +    void updateByIsReadTrueByMessageId(@Param("messageId") Long messageId);
업데이트 같은 경우 JPA의 dirtyChecking을 쓰지 않을 경우 db에는 반영되지만 영속성 컨테스트에 해당 업데이트가 반영이 안되어서, 오류가 발생할 수 있기 때문에 가급적 @Transcational환경에서 dirty checking으로 update바람

2024-11-05 05:09 UTC, sms3025 commented on src/main/java/LinkerBell/campus_market_spring/repository/ChatMessageRepository.java
> +    void updateByIsReadTrueByMessageId(@Param("messageId") Long messageId);
추가로 여기 이외에도 updateQuery로 쓴 곳이 많던데 그게 적절한지 한번 생각해보기 바람

2024-11-05 05:17 UTC, ajou4095 commented on src/main/java/LinkerBell/campus_market_spring/global/error/ErrorCode.java
> +    MESSAGE_NOT_FOUND(HttpStatus.NOT_FOUND, 4027, "채팅 메시지가 존재하지 않습니다."),
누가 먼저 머지될지 모르는데 다른사람 머지가 되면 그때 수정해야함

2024-11-07 03:38 UTC, closed without merging